name: CI/CD - .NET API
permissions:
  contents: read

on:
  workflow_dispatch:   # permite execuÃ§Ã£o manual
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------
  # 1ï¸âƒ£ CI -Build & Test
  # ------------------------------
  build-and-test:
    name: ðŸ§ª CI - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  # ------------------------------
  # 2ï¸âƒ£ Deploy - Staging
  # ------------------------------
  deploy-staging:
    name: ðŸš€ Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh

      - name: Login to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN_STAGING }}
        run: railway login --apiKey $RAILWAY_API_TOKEN

      - name: Deploy to Railway (Staging)
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          ASPNETCORE_ENVIRONMENT: Staging
        run: |
          echo "Deploying to Staging..."
          dotnet publish -c Release -o ./publish
          railway up --project 5ffae6e4-7251-474c-aada-2c136be60c08
          echo "https://catalog-api-staging.up.railway.app"
          echo "url=https://catalog-api-staging.up.railway.app" >> $GITHUB_OUTPUT

  # ------------------------------
  # 3ï¸âƒ£ Deploy - Production
  # ------------------------------
  deploy-production:
    name: ðŸš€ Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh

      - name: Login to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN_PRODUCTION }}
        run: railway login --apiKey $RAILWAY_API_TOKEN

      - name: Deploy to Railway (Production)
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          ASPNETCORE_ENVIRONMENT: Production
        run: |
          echo "Deploying to Production..."
          dotnet publish -c Release -o ./publish
          railway up --project 5ffae6e4-7251-474c-aada-2c136be60c08
          echo "https://catalog-api-da-ale.up.railway.app"
          echo "url=https://catalog-api-da-ale.up.railway.app" >> $GITHUB_OUTPUT
